
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 19 17:02:15 CET 2012
//----------------------------------------------------

package MyGCC;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LHOOK = 5;
  public static final int LBRACKET = 9;
  public static final int EQUALS = 24;
  public static final int LPAREN = 7;
  public static final int GREATER = 23;
  public static final int SEMI = 12;
  public static final int INT = 2;
  public static final int LESS = 22;
  public static final int MINUS = 20;
  public static final int STATIC = 4;
  public static final int RPAREN = 8;
  public static final int NOT = 21;
  public static final int AND = 33;
  public static final int OR = 32;
  public static final int COMMA = 11;
  public static final int DIV = 30;
  public static final int RHOOK = 6;
  public static final int NB_INT = 35;
  public static final int PLUS = 28;
  public static final int EXIT = 14;
  public static final int IF = 17;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 10;
  public static final int error = 1;
  public static final int MOD = 31;
  public static final int IDENT = 34;
  public static final int VOID = 3;
  public static final int TIMES = 29;
  public static final int READ_INT = 16;
  public static final int ELSE = 18;
  public static final int WHILE = 19;
  public static final int EQL = 13;
  public static final int DIFF = 27;
  public static final int GEQL = 26;
  public static final int LEQL = 25;
}

